platform :ios, ‘8.0’

target 'hongyu' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hongyu

    pod 'SDWebImage', '~> 3.8.2'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'Masonry', '~> 1.0.2'
    pod 'FMDB', '~> 2.6.2'
    pod 'SVProgressHUD', '~> 2.0.3'
    pod 'SDCycleScrollView', '~> 1.65'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'YYModel', '~> 1.0.4'
    pod 'TPKeyboardAvoiding', '~> 1.3'
    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'ActionSheetPicker-3.0'
    pod 'MJExtension', '~> 3.0.13'

end
